
version: '3.9'
services:
  app:
    build: .
    command: [ "wait-for-it", "selenium:4444", "--", "gosu", "user", "python3", "main.py" ]
    environment:
      PLAYLIST_URL: ${PLAYLIST_URL:?set PLAYLIST_URL}
      ROOT_DIR: /data
      SELENIUM_URL: http://selenium:4444/wd/hub
    volumes:
      - '${ROOT_DIR:?set ROOT_DIR}:/data'
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome:101.0
    volumes:
      - /dev/shm:/dev/shm
