
version: '3.9'
services:
  app:
    build: .
    entrypoint: [ "wait-for-it", "selenium:4444", "--", "gosu", "user", "python3", "main.py" ]
    environment:
      AMPD_SELENIUM_URL: http://selenium:4444/wd/hub
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:113.0
    volumes:
      - /dev/shm:/dev/shm
